### ISSUE TITLE
Search by date (GOES and NEXRAD)

### ISSUE THREAD

**Issue by shankar-dh** [BigDataIA-Spring2023-Team-09/DAMG_7245#13]
The URL to File’s NOAA bucket is displayed instead of giving the entire link

- Issue raised by Team7

**Comment by Hmittal15** [comment]
Since it was mentioned in the requirement "You should also provide the link to the GOES site from where you did the transfer so users can compare the files", we interpreted that we needed to provide the link of site where the file resides. So, we provided the link to NOAA's bucket and not entire file link. Anyways, post clarification, we fixed this in Assignment 2 and are now providing the complete file link.
